services:
  postgres_dev:
    build:
      context: ./Docker/Postgres
      dockerfile: Postgres.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Boilerplate
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
  apache_dev:
    build:
      context: ./Docker/Apache
      dockerfile: Apache.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443
    environment:
      - API_URL=http://host.docker.internal:5044/api
      - SERVER_NAME=www.boilerplate.com
      - SERVER_ALIAS=*.boilerplate.com
      - FRONTEND_URL=http://host.docker.internal:5173/