name: Deploy application
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "💡 The ${{ gitea }} repository has been cloned to the runner."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          docker build -t ${{ env.REGISTRY }}/boilerplate-frontend:latest -f Docker/Frontend/Dockerfile .
      - run: echo "🍏 This job's status is ${{ job.status }}."